openapi: "3.0.0"
info:
  title: Example Booking API
  version: 1.0.0
servers:
  - url: https://localhost:8433/v1
  - url: http://localhost:8080/v1
schemes:
  - http
  - https
paths:
  /properties:
    get:
      operationId: getProperties
      summary: Gets available properties
      parameters:
        - name: at
          in: query
          description: Geolocation to retrieve properties for in `[latitude],[longitude]` format
          example: "48.1366,11.577"
          required: true
          schema:
            type: string
            pattern: '^\d+(\.\d+)?,\d+(\.\d+)?$'
      responses:
        "200":
          description: List of properties
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Property"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /properties/{propertyId}/bookings:
    get:
      operationId: getPropertyBookings
      summary: Gets bookings for property
      parameters:
        - name: propertyId
          in: path
          description: ID of property
          example: hotelbeach
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of bookings
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/BookingWithUser"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /bookings:
    get:
      operationId: getBookings
      summary: Gets bookings
      responses:
        "200":
          description: List of bookings
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/BookingWithUser"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: createBookings
      summary: Book property
      requestBody:
        description: Booking to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewBookingWithUser"
      responses:
        "200":
          description: Created booking
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/BookingWithUser"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /users/{userId}/bookings:
    get:
      operationId: getUserBookings
      summary: Gets bookings for user
      parameters:
        - name: userId
          in: path
          description: ID of user
          example: joe
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of bookings
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Booking"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Booking:
      allOf:
        - $ref: "#/components/schemas/NewBooking"
        - type: object
          properties:
            id:
              type: string
      example:
        id: booking-1
        property_id: hotelbeach
        property_name: Hotel at the beach
        property_location: Venice
    NewBooking:
      type: object
      properties:
        property_id:
          type: string
        property_name:
          type: string
        property_location:
          type: string
      example:
        property_id: hotelbeach
        property_name: Hotel at the beach
        property_location: Venice
    BookingWithUser:
      allOf:
        - $ref: "#/components/schemas/Booking"
        - type: object
          properties:
            user:
              $ref: "#/components/schemas/User"
      example:
        id: booking-1
        property_id: hotelbeach
        property_name: Hotel at the beach
        property_location: Venice
        user:
          id: joe
          name: Joe Fisher
    NewBookingWithUser:
      allOf:
        - $ref: "#/components/schemas/NewBooking"
        - type: object
          properties:
            user:
              $ref: "#/components/schemas/NewUser"
      example:
        property_id: hotelbeach
        property_name: Hotel at the beach
        property_location: Venice
        user:
          name: Joe Fisher
    Property:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        distance:
          type: integer
          format: int32
          description: Distance from given location in meters
        location:
          type: string
          description: Textual description of property location
      example:
        id: hotelbeach
        name: Hotel at the beach
        distance: 102
        location: "Beach\n12345 Beachington"
    User:
      allOf:
        - $ref: "#/components/schemas/NewUser"
        - type: object
          properties:
            id:
              type: string
      example:
        id: joe
        name: Joe Fisher
    NewUser:
      type: object
      properties:
        name:
          type: string
      example:
        name: Joe Fisher
    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: Status code of error response
          example: 404
        message:
          type: string
          description: Description of error
